# 基础镜像
FROM openjdk:8-jdk-alpine
# author
MAINTAINER zdb

# 挂载目录
VOLUME /home/web
# 创建目录
RUN mkdir -p /home/web
# 指定路径
WORKDIR /home/web
# 复制jar文件到路径
COPY ./jar/web.jar /home/web/web.jar
# 启动文件服务
ENTRYPOINT ["java","-jar","web.jar"]